change

diff --git a/.github/workflows/delivery.yml b/.github/workflows/delivery.yml
--- a/.github/workflows/delivery.yml
+++ b/.github/workflows/delivery.yml
@@ -18,14 +18,14 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
         with:
-          ref: ${{ github.event.inputs.tag }}
+         ref: ${{ github.event.inputs.tag }}
       - name: Check if tag exists
         run: |
-                   git fetch --all --tags
-                   if ! git tag | grep -q "^${{ github.event.inputs.tag }}$"; then
-                     echo "error: Tag '${{ github.event.inputs.tag }}' not found"
-                     exit 1
-                   fi
+          git fetch --all --tags
+          if ! git tag | grep -q "^${{ github.event.inputs.tag }}$"; then
+            echo "error: Tag '${{ github.event.inputs.tag }}' not found"
+            exit 1
+          fi
       - name: Create workdir
         run: |
           sudo apt-get install ssh
